-- 手动执行字典数据初始化脚本
-- 如果字典管理中没有数据，可以手动执行此脚本

-- 清空现有数据（可选，如果需要重新初始化）
-- TRUNCATE TABLE bp_sys_dict_item;

-- 插入字典数据
INSERT IGNORE INTO bp_sys_dict_item (dict_type, dict_label, dict_value, tag_type, sort_order, status, disabled, remark) VALUES
('order_status', '已支付', 'PAID', 'success', 1, 1, 0, ''),
('order_status', '待支付', 'PENDING', 'warning', 2, 1, 0, ''),
('order_status', '已退款', 'REFUNDED', 'danger', 3, 1, 0, ''),
('order_status', '已超时', 'TIMEOUT', 'info', 4, 1, 0, ''),
('user_status', '正常', '1', 'success', 1, 1, 0, ''),
('user_status', '禁用', '0', 'danger', 2, 1, 0, ''),
('vip_status', 'VIP用户', '1', 'warning', 1, 1, 0, ''),
('vip_status', '普通用户', '0', 'info', 2, 1, 0, ''),
('pattern_status', '待审核', '0', 'warning', 1, 1, 0, ''),
('pattern_status', '已上线', '1', 'success', 2, 1, 0, ''),
('pattern_status', '已下线', '2', 'info', 3, 1, 0, ''),
('pattern_status', '未通过', '3', 'danger', 4, 1, 0, ''),
('banner_action_type', '小程序内跳转', 'NAVIGATE', 'primary', 1, 1, 0, ''),
('banner_action_type', '活动详情页', 'ACTIVITY', 'success', 2, 1, 0, ''),
('banner_action_type', '领取礼品包', 'CLAIM_GIFT', 'warning', 3, 1, 0, ''),
('banner_action_type', '外部链接', 'EXTERNAL', 'info', 4, 1, 0, ''),
('banner_action_type', '无动作', 'NONE', 'info', 5, 1, 0, ''),
('banner_claim_limit', '每人仅一次', 'ONCE', 'warning', 1, 1, 0, ''),
('banner_claim_limit', '每日一次', 'DAILY', 'primary', 2, 1, 0, ''),
('banner_link_type', '无跳转', 'NONE', 'info', 1, 1, 0, '兼容旧 Banner linkType'),
('banner_link_type', '小程序页面', 'PAGE', 'primary', 2, 1, 0, ''),
('banner_link_type', '外部链接', 'URL', 'warning', 3, 1, 0, ''),
('miniapp_route_page', '首页', '/pages/home/home', 'info', 1, 1, 0, ''),
('miniapp_route_page', '图片转图纸', '/pages/convert/convert', 'info', 2, 1, 0, ''),
('miniapp_route_page', 'AI 生成', '/pages/ai-generate/ai-generate', 'info', 3, 1, 0, ''),
('miniapp_route_page', '我的', '/pages/profile/profile', 'info', 4, 1, 0, ''),
('miniapp_route_page', '生成页', '/pages/generate/generate', 'info', 5, 1, 0, ''),
('miniapp_route_page', '时光机', '/pages/history/history', 'info', 6, 1, 0, ''),
('miniapp_route_page', '图纸箱', '/pages/my-patterns/my-patterns', 'info', 7, 1, 0, ''),
('miniapp_route_page', '画板', '/pages/draw/draw', 'info', 8, 1, 0, ''),
('miniapp_route_page', '生成中', '/pages/generating/generating', 'info', 9, 1, 0, ''),
('miniapp_route_page', '结果页', '/pages/result/result', 'info', 10, 1, 0, ''),
('miniapp_route_page', '专注模式', '/pages/focus-mode/focus-mode', 'info', 11, 1, 0, ''),
('miniapp_route_page', 'VIP', '/pages/vip/vip', 'info', 12, 1, 0, ''),
('activity_type', '内容页', 'CONTENT', 'info', 1, 1, 0, ''),
('activity_type', '礼品活动', 'GIFT', 'success', 2, 1, 0, ''),
('activity_button_action', '无按钮动作', 'NONE', 'info', 1, 1, 0, ''),
('activity_button_action', '小程序内跳转', 'NAVIGATE', 'primary', 2, 1, 0, ''),
('activity_button_action', '外部链接', 'EXTERNAL', 'warning', 3, 1, 0, ''),
('activity_button_action', '立即领取', 'CLAIM', 'success', 4, 1, 0, ''),
('activity_button_action', '跳转(兼容旧数据)', 'JUMP', 'info', 5, 1, 0, ''),
('activity_button_action', '充值(兼容旧数据)', 'RECHARGE', 'warning', 6, 1, 0, ''),
('activity_limit_type', '每人一次', 'ONCE', 'warning', 1, 1, 0, ''),
('activity_limit_type', '每日一次', 'DAILY', 'primary', 2, 1, 0, ''),
('activity_limit_type', '不限制', 'UNLIMITED', 'success', 3, 1, 0, ''),
('gift_type_value_type', '数字面值', 'number', 'info', 1, 1, 0, ''),
('gift_type_value_type', '折扣', 'discount', 'warning', 2, 1, 0, ''),
('gift_type_value_type', '天数', 'days', 'success', 3, 1, 0, ''),
('gift_type_value_type', '次数', 'times', 'primary', 4, 1, 0, ''),
('gift_type_value_type', '金币', 'coins', 'warning', 5, 1, 0, ''),
('gift_type_target_product', '会员卡', 'vip', 'success', 1, 1, 0, ''),
('gift_type_target_product', '次卡', 'card', 'primary', 2, 1, 0, ''),
('gift_type_target_product', '全部商品', 'all', 'info', 3, 1, 0, ''),
('gift_type_status', '启用', '1', 'success', 1, 1, 0, ''),
('gift_type_status', '停用', '0', 'info', 2, 1, 0, ''),
('image_task_type', '图片转图纸', 'BEAD_LOCAL', 'info', 1, 1, 0, ''),
('image_task_type', 'AI生成', 'BEAD_AI', 'primary', 2, 1, 0, ''),
('image_task_status', '成功', 'SUCCESS', 'success', 1, 1, 0, ''),
('image_task_status', '进行中', 'CREATED', 'warning', 2, 1, 0, ''),
('image_task_status', '失败', 'FAILED', 'danger', 3, 1, 0, ''),
('image_task_saved', '已保存', '1', 'success', 1, 1, 0, ''),
('image_task_saved', '未保存', '0', 'info', 2, 1, 0, ''),
('task_handler_type', '签到模块入口（固定模块）', 'CHECKIN', 'primary', 1, 1, 0, ''),
('task_handler_type', '邀请好友注册', 'INVITE_REGISTER', 'success', 2, 1, 0, ''),
('task_handler_type', '邀请好友充值', 'INVITE_RECHARGE', 'warning', 3, 1, 0, ''),
('task_handler_type', '注册礼包', 'REGISTER_GIFT', 'info', 4, 1, 0, ''),
('task_handler_type', '首冲礼包', 'FIRST_RECHARGE_GIFT', 'info', 5, 1, 0, ''),
('task_handler_type', '审核型任务', 'REVIEW_TASK', 'danger', 6, 1, 0, ''),
('task_handler_type', '通用进度任务', 'GENERIC_PROGRESS', 'primary', 7, 1, 0, ''),
('task_handler_type', '事件任务入口', 'EVENT_TASK', 'warning', 8, 1, 0, ''),
('task_center_task_type', '每日', 'DAILY', 'primary', 1, 1, 0, ''),
('task_center_task_type', '一次性', 'ONCE', 'success', 2, 1, 0, ''),
('task_center_task_type', '无限制', 'UNLIMITED', 'warning', 3, 1, 0, ''),
('task_reward_display_type', 'AI生成次数', 'AI_COUNT', 'primary', 1, 1, 0, ''),
('task_reward_display_type', '会员天数', 'VIP_DAYS', 'success', 2, 1, 0, ''),
('task_reward_display_type', '优惠券', 'COUPON', 'warning', 3, 1, 0, ''),
('review_submission_status', '待审核', '0', 'warning', 1, 1, 0, ''),
('review_submission_status', '已通过', '1', 'success', 2, 1, 0, ''),
('review_submission_status', '已驳回', '2', 'danger', 3, 1, 0, ''),
('feedback_status', '待处理', '0', 'warning', 1, 1, 0, ''),
('feedback_status', '处理中', '1', 'info', 2, 1, 0, ''),
('feedback_status', '已回复', '2', 'success', 3, 1, 0, ''),
('feedback_status', '已关闭', '3', 'info', 4, 1, 0, ''),
('feedback_category', 'Bug', 'BUG', 'danger', 1, 1, 0, ''),
('feedback_category', '建议', 'OTHER', 'info', 2, 1, 0, ''),
('feedback_category', '建议', 'SUGGESTION', 'info', 3, 1, 0, '兼容旧分类值'),
('tutorial_status', '上线', '1', 'success', 1, 1, 0, ''),
('tutorial_status', '下线', '0', 'info', 2, 1, 0, ''),
('popup_enabled', '启用', '1', 'success', 1, 1, 0, ''),
('popup_enabled', '禁用', '0', 'info', 2, 1, 0, ''),
('status_enable', '启用', '1', 'success', 1, 1, 0, ''),
('status_enable', '停用', '0', 'info', 2, 1, 0, ''),
('status_online', '上线', '1', 'success', 1, 1, 0, ''),
('status_online', '下线', '0', 'info', 2, 1, 0, '');

-- 查询插入结果
SELECT COUNT(*) as total_count FROM bp_sys_dict_item;
SELECT dict_type, COUNT(*) as count FROM bp_sys_dict_item GROUP BY dict_type ORDER BY dict_type;
