CREATE TABLE IF NOT EXISTS bp_analytics_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_event_id VARCHAR(64) NOT NULL,
  event_name VARCHAR(64) NOT NULL,
  event_time DATETIME NOT NULL,
  server_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT NULL,
  session_id VARCHAR(64) NOT NULL,
  page VARCHAR(128) NOT NULL,
  refer_page VARCHAR(128) NULL,
  source VARCHAR(64) NULL,
  is_login TINYINT(1) NULL,
  is_vip TINYINT(1) NULL,
  vip_level VARCHAR(32) NULL,
  pattern_id VARCHAR(64) NULL,
  pattern_source VARCHAR(32) NULL,
  result VARCHAR(32) NULL,
  fail_reason VARCHAR(64) NULL,
  params_json TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_analytics_client_event_id (client_event_id),
  KEY idx_analytics_event_time_name (event_time, event_name),
  KEY idx_analytics_server_time_name (server_time, event_name),
  KEY idx_analytics_source_time (source, event_time),
  KEY idx_analytics_user_time (user_id, event_time),
  KEY idx_analytics_session_time (session_id, event_time)
) DEFAULT CHARSET=utf8mb4 COMMENT='Mini program analytics raw events';

CREATE TABLE IF NOT EXISTS bp_analytics_event_dict (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_name VARCHAR(64) NOT NULL,
  event_cn_name VARCHAR(64) NOT NULL,
  category VARCHAR(32) NOT NULL,
  importance VARCHAR(16) NOT NULL,
  description VARCHAR(255) NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_analytics_event_name (event_name)
) DEFAULT CHARSET=utf8mb4 COMMENT='Analytics event dictionary';

CREATE TABLE IF NOT EXISTS bp_analytics_event_daily (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stat_date DATE NOT NULL,
  event_name VARCHAR(64) NOT NULL,
  page VARCHAR(128) NOT NULL DEFAULT '',
  source VARCHAR(64) NOT NULL DEFAULT '',
  pattern_source VARCHAR(32) NOT NULL DEFAULT '',
  result VARCHAR(32) NOT NULL DEFAULT '',
  user_count BIGINT NOT NULL DEFAULT 0,
  session_count BIGINT NOT NULL DEFAULT 0,
  event_count BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_analytics_daily_dim (stat_date, event_name, page, source, pattern_source, result),
  KEY idx_analytics_daily_event (event_name, stat_date),
  KEY idx_analytics_daily_date (stat_date)
) DEFAULT CHARSET=utf8mb4 COMMENT='Analytics daily aggregate';

INSERT INTO bp_analytics_event_dict (event_name, event_cn_name, category, importance, description)
VALUES
('page_home_view', '浏览首页', 'page', 'P0', '首页 onShow'),
('page_convert_view', '浏览图片转图纸页', 'page', 'P0', '图片转图纸页 onShow'),
('page_ai_generate_view', '浏览 AI 生成页', 'page', 'P0', 'AI 生成页 onShow'),
('page_preview_view', '浏览图纸预览页', 'page', 'P0', '预览页 onShow'),
('page_draw_view', '浏览画板编辑页', 'page', 'P0', '画板页 onShow'),
('page_focus_view', '浏览沉浸式拼豆页', 'page', 'P0', '沉浸式拼豆页 onShow'),
('page_pattern_box_view', '浏览图纸箱', 'page', 'P1', '图纸箱 onShow'),
('page_history_view', '浏览时光机', 'page', 'P1', '时光机 onShow'),
('page_draft_view', '浏览草稿箱', 'page', 'P1', '草稿箱 onShow'),
('page_profile_view', '浏览我的页', 'page', 'P0', '我的页 onShow'),
('convert_image_upload_click', '点击上传图片', 'core', 'P0', '图片转图纸点击上传'),
('convert_image_upload_result', '图片上传结果', 'core', 'P0', '上传成功或失败'),
('convert_param_confirm', '确认免费生成参数', 'core', 'P0', '参数页点击生成'),
('convert_generate_result', '免费图纸生成结果', 'core', 'P0', '生成结束'),
('ai_image_upload_result', 'AI 图片上传结果', 'core', 'P0', 'AI 页上传成功或失败'),
('ai_generate_click', '点击 AI 生成', 'core', 'P0', 'AI 页点击生成'),
('ai_generate_result', 'AI 生成结果', 'core', 'P0', 'AI 任务成功或失败'),
('preview_tab_switch', '预览页切换 Tab', 'core', 'P1', '预览页 Tab 切换'),
('preview_edit_click', '点击编辑图纸', 'core', 'P0', '预览页点击编辑'),
('preview_save_click', '点击保存图纸', 'core', 'P0', '预览页点击保存'),
('draw_tool_use', '使用画板工具', 'core', 'P1', '工具切换或执行'),
('draw_save_result', '画板保存结果', 'core', 'P0', '画板保存成功或失败'),
('focus_progress_mark', '沉浸式拼豆标记进度', 'core', 'P0', '标记格子/颜色完成'),
('focus_progress_save_result', '沉浸式进度保存结果', 'core', 'P0', '自动/手动保存结束'),
('quota_panel_view', 'AI 魔法次数面板曝光', 'payment', 'P0', '面板打开'),
('quota_empty_panel_view', 'AI 次数不足面板曝光', 'payment', 'P0', '次数为 0 时触发'),
('recharge_center_view', '浏览充值中心', 'payment', 'P0', '充值中心 onShow'),
('vip_product_click', '点击会员套餐', 'payment', 'P0', '点击会员卡套餐'),
('card_product_click', '点击次卡套餐', 'payment', 'P0', '点击 AI 次卡套餐'),
('payment_create_result', '创建支付单结果', 'payment', 'P0', '调后端下单结束'),
('payment_result', '微信支付结果', 'payment', 'P0', 'wx.requestPayment 回调'),
('rewarded_ad_click', '点击激励广告', 'payment', 'P1', '点击看广告领次数'),
('rewarded_ad_result', '激励广告结果', 'payment', 'P1', '广告看完/失败/取消'),
('task_panel_view', '任务中心面板曝光', 'payment', 'P1', '任务面板打开'),
('pattern_box_save_result', '保存至图纸箱结果', 'storage', 'P0', '保存结束'),
('draft_save_result', '保存草稿结果', 'storage', 'P1', '草稿保存结束'),
('capacity_limit_hit', '触发容量上限', 'storage', 'P0', '保存被容量限制拦截'),
('pattern_delete_result', '删除图纸结果', 'storage', 'P1', '删除结束'),
('history_restore_click', '点击时光机恢复', 'storage', 'P1', '时光机点击恢复'),
('share_initiate', '发起分享', 'growth', 'P0', 'onShareAppMessage 或分享按钮'),
('share_visit', '分享访问', 'growth', 'P0', '通过分享参数进入'),
('invite_bind_result', '邀请关系绑定结果', 'growth', 'P0', '新用户绑定邀请关系后'),
('reward_grant_result', '奖励发放结果', 'growth', 'P0', '邀请/任务/广告奖励到账'),
('notification_open', '通知打开', 'growth', 'P1', '点击站内/订阅通知进入')
ON DUPLICATE KEY UPDATE
  event_cn_name = VALUES(event_cn_name),
  category = VALUES(category),
  importance = VALUES(importance),
  description = VALUES(description),
  enabled = 1;
