CREATE TABLE IF NOT EXISTS bp_ai_magic_style (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  icon VARCHAR(512) NULL,
  tag VARCHAR(64) NULL,
  description VARCHAR(256) NULL,
  prompt_template VARCHAR(512) NULL,
  negative_prompt_template VARCHAR(1024) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_enabled_sort (enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI magic style config';

CREATE TABLE IF NOT EXISTS bp_vip_package (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  package_code VARCHAR(64) NOT NULL UNIQUE,
  midas_product_id VARCHAR(128) NULL,
  package_name VARCHAR(128) NOT NULL,
  duration_days INT NOT NULL DEFAULT 30,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  original_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  ai_quota_gift INT NOT NULL DEFAULT 0,
  tag VARCHAR(64) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  purchase_limit INT NULL,
  shelf_start_time DATETIME NULL,
  shelf_end_time DATETIME NULL,
  vip_only TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='VIP package config';

CREATE TABLE IF NOT EXISTS bp_card_package (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  package_code VARCHAR(64) NOT NULL UNIQUE,
  midas_product_id VARCHAR(128) NULL,
  package_name VARCHAR(128) NOT NULL,
  ai_quota INT NOT NULL DEFAULT 1,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  original_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  vip_price DECIMAL(10,2) NULL,
  tag VARCHAR(64) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  purchase_limit INT NULL,
  shelf_start_time DATETIME NULL,
  shelf_end_time DATETIME NULL,
  vip_only TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Card package config';

CREATE TABLE IF NOT EXISTS bp_popup_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  `key` VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(128) NOT NULL,
  content TEXT NULL,
  image_url VARCHAR(1024) NULL,
  button_text VARCHAR(64) NULL,
  button_url VARCHAR(512) NULL,
  priority INT NOT NULL DEFAULT 0,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  start_time DATETIME NULL,
  end_time DATETIME NULL,
  show_interval INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_active_time (enabled, start_time, end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Popup config';
