-- 水印配置表
CREATE TABLE IF NOT EXISTS bp_watermark_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用水印：0=禁用 1=启用',
    text VARCHAR(128) NULL COMMENT '水印文字，如"拼豆小程序"',
    font_size INT NOT NULL DEFAULT 24 COMMENT '字体大小',
    color VARCHAR(16) NOT NULL DEFAULT 'rgba(128,128,128,0.5)' COMMENT '水印颜色',
    position VARCHAR(16) NOT NULL DEFAULT '右下' COMMENT '位置：右下/左下/平铺',
    opacity DECIMAL(3,2) NOT NULL DEFAULT 0.50 COMMENT '透明度：0.00-1.00',
    margin INT NOT NULL DEFAULT 20 COMMENT '边距',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
