CREATE TABLE IF NOT EXISTS `bp_sys_dict_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `dict_type` varchar(64) NOT NULL COMMENT '字典类型编码',
  `dict_label` varchar(128) NOT NULL COMMENT '展示标签',
  `dict_value` varchar(128) NOT NULL COMMENT '选项值（与业务存储一致）',
  `tag_type` varchar(32) NOT NULL DEFAULT 'info' COMMENT 'Element Plus tag 类型',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '同类型内排序',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0停用 1启用',
  `disabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否禁用可选',
  `remark` varchar(256) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_type_value` (`dict_type`,`dict_value`),
  KEY `idx_dict_type_status` (`dict_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统字典项';

INSERT IGNORE INTO bp_sys_dict_item (dict_type, dict_label, dict_value, tag_type, sort_order, status, disabled, remark) VALUES
('order_status', '已支付', 'PAID', 'success', 1, 1, 0, ''),
('order_status', '待支付', 'PENDING', 'warning', 2, 1, 0, ''),
('order_status', '已退款', 'REFUNDED', 'danger', 3, 1, 0, ''),
('user_status', '正常', '1', 'success', 1, 1, 0, ''),
('user_status', '禁用', '0', 'danger', 2, 1, 0, ''),
('vip_status', 'VIP用户', '1', 'warning', 1, 1, 0, ''),
('vip_status', '普通用户', '0', 'info', 2, 1, 0, ''),
('pattern_status', '待审核', '0', 'warning', 1, 1, 0, ''),
('pattern_status', '已上线', '1', 'success', 2, 1, 0, ''),
('pattern_status', '已下线', '2', 'info', 3, 1, 0, ''),
('pattern_status', '未通过', '3', 'danger', 4, 1, 0, ''),
('banner_action_type', '小程序内跳转', 'NAVIGATE', 'primary', 1, 1, 0, ''),
('banner_action_type', '活动详情页', 'ACTIVITY', 'success', 2, 1, 0, ''),
('banner_action_type', '领取礼品包', 'CLAIM_GIFT', 'warning', 3, 1, 0, ''),
('banner_action_type', '外部链接', 'EXTERNAL', 'info', 4, 1, 0, ''),
('banner_action_type', '无动作', 'NONE', 'info', 5, 1, 0, ''),
('banner_claim_limit', '每人仅一次', 'ONCE', 'warning', 1, 1, 0, ''),
('banner_claim_limit', '每日一次', 'DAILY', 'primary', 2, 1, 0, ''),
('activity_type', '内容页', 'CONTENT', 'info', 1, 1, 0, ''),
('activity_type', '礼品活动', 'GIFT', 'success', 2, 1, 0, ''),
('activity_button_action', '无按钮动作', 'NONE', 'info', 1, 1, 0, ''),
('activity_button_action', '小程序内跳转', 'NAVIGATE', 'primary', 2, 1, 0, ''),
('activity_button_action', '外部链接', 'EXTERNAL', 'warning', 3, 1, 0, ''),
('activity_button_action', '立即领取', 'CLAIM', 'success', 4, 1, 0, ''),
('activity_button_action', '跳转(兼容旧数据)', 'JUMP', 'info', 5, 1, 0, ''),
('activity_button_action', '充值(兼容旧数据)', 'RECHARGE', 'warning', 6, 1, 0, ''),
('activity_limit_type', '每人一次', 'ONCE', 'warning', 1, 1, 0, ''),
('activity_limit_type', '每日一次', 'DAILY', 'primary', 2, 1, 0, ''),
('activity_limit_type', '不限制', 'UNLIMITED', 'success', 3, 1, 0, ''),
('gift_type_value_type', '数字面值', 'number', 'info', 1, 1, 0, ''),
('gift_type_value_type', '折扣', 'discount', 'warning', 2, 1, 0, ''),
('gift_type_value_type', '天数', 'days', 'success', 3, 1, 0, ''),
('gift_type_value_type', '次数', 'times', 'primary', 4, 1, 0, ''),
('gift_type_value_type', '金币', 'coins', 'warning', 5, 1, 0, ''),
('gift_type_target_product', '会员卡', 'vip', 'success', 1, 1, 0, ''),
('gift_type_target_product', '次卡', 'card', 'primary', 2, 1, 0, ''),
('gift_type_target_product', '全部商品', 'all', 'info', 3, 1, 0, ''),
('gift_type_status', '启用', '1', 'success', 1, 1, 0, ''),
('gift_type_status', '停用', '0', 'info', 2, 1, 0, '');
